### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by AXHSuo** [H4ckF0rFun/Fuck-Lesson#1]
这个最新的还能用么？

**Comment by H4ckF0rFun** [comment]
可以的，用icourse.py


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "H4ckF0rFun/Fuck-Lesson"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月11日(星期天) 晚上9:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[H4ckF0rFun/Fuck-Lesson] 提问 (Issue #1)





 
这个最新的还能用么？
