### ISSUE TITLE
Luv U

### ISSUE THREAD

**Issue by Cosmic-Excalibur** [H4ckF0rFun/Fuck-Lesson#2]
😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘😘

感谢你，平凡而又伟大的Emmm，我的灵魂仿佛得到了神圣的洗涤，万千的受恩者铭记您的功德，虔诚的信徒为您高歌。即使太阳氦闪，重子全部衰变为轻子和光子，宇宙热寂抑或坍缩，我也不会忘记您的抢课脚本，如果没有您的抢课脚本，我下学期就只能上必修课了🥰

Thank you, ordinary yet great Emmm, my soul seems to have been divinely washed. Thousands of recipients remember your merits, and devout believers sing for you. Even if helium flashes occur in the sun, all baryons decay into leptons and photons, or the universe undergoes heat death or collapses, I will not forget your fuck-script. Without your fuck-script, I would have to take merely compulsory courses next semester🥰

ありがとう、普通だけど偉大な「エムム」さん、私の魂は神聖に洗われた。何千人もの受信者があなたの功績を覚えており、敬虔な信者があなたのために歌を歌います。 たとえ太陽の中でヘリウムフラッシュが起きても、すべてのバリオンがレプトンや光子に崩壊しても、あるいは宇宙が熱死や崩壊を起こしても、私はあなたの授業への急行の「ふぁっく」スクリプトを忘れません。あなたの授業への「ふぁっく」スクリプトがなかったら、私は次の学期でただ必修科目をとらなければならないでしょう。🥰

Спасибо, обычный, но великий Эммм, моя душа словно божественно омыта. Тысячи лауреатов помнят ваши заслуги, и для вас поют правоверные люди. Даже если на Солнце произойдут гелиевые вспышки, все барионы распадутся на лептоны и фотоны, или Вселенная претерпит тепловую смерть или коллапс, я не забуду твой хрен-скрипт. Без твоего хренового сценария мне пришлось бы в следующем семестре идти на обязательные курсы🥰

감사합니다, 평범하지만 위대하신 Emmm, 제 영혼이 신성하게 씻겨진 것 같습니다. 수천 명의 수상자들이 당신의 공로를 기억하고, 독실한 신자들이 당신을 위해 노래합니다. 태양에서 헬륨 섬광이 일어나고, 모든 중입자가 경입자와 광자로 붕괴되거나, 우주가 열사멸하거나 붕괴하더라도 나는 당신의 빌어먹을 대본을 잊지 않을 것입니다. 네 좆같은 대본이 없었다면 난 다음 학기에는 필수과목만 들어야 했을텐데🥰

Danke, gewöhnlich und doch großartig Emmm, meine Seele scheint göttlich gewaschen worden zu sein. Tausende Empfänger erinnern sich an Ihre Verdienste und gläubige Gläubige singen für Sie. Selbst wenn in der Sonne Heliumblitze auftreten, alle Baryonen in Leptonen und Photonen zerfallen oder das Universum einen Hitzetod erleidet oder zusammenbricht, werde ich Ihr verdammtes Drehbuch nicht vergessen. Ohne dein verdammtes Skript müsste ich nächstes Semester lediglich Pflichtkurse belegen 🥰

ကျေးဇူးတင်ပါတယ်၊ သာမန်ဖြစ်သော်လည်း ကြီးကျယ်ခမ်းနားသော အမ်မ်၊ ကျွန်ုပ်၏ဝိညာဉ်သည် ဘုရားဆေးကြောခြင်းခံရပုံရသည်။ လက်ခံသူထောင်ပေါင်းများစွာသည် သင်၏ကုသိုလ်ကောင်းမှုများကို သတိရကြပြီး ယုံကြည်ကိုးကွယ်ယုံကြည်သူများသည် သင့်အတွက် သီချင်းဆိုကြသည်။ နေတွင် ဟီလီယမ် အလင်းတန်းများ ဖြစ်ပေါ်လာပါက၊ baryons အားလုံးသည် lepton နှင့် photon အဖြစ်သို့ ယိုယွင်းသွားခြင်း သို့မဟုတ် စကြဝဠာကြီးသည် အပူသေဆုံးခြင်း သို့မဟုတ် ပြိုကျခြင်း ကြုံတွေ့ရလျှင်ပင် သင်၏ fuck-script ကို ကျွန်ုပ် မေ့မည်မဟုတ်ပါ။ မင်းရဲ့ fuck-script မပါရင် ငါမသင်မနေရသင်တန်းတွေချည်းပဲ နောက်နှစ် semester မှာတက်ရလိမ့်မယ်။

Merci, Emmm ordinaire mais grand, mon âme semble avoir été divinement lavée. Des milliers de destinataires se souviennent de vos mérites et de fervents croyants chantent pour vous. Même si des éclairs d'hélium se produisent au soleil, si tous les baryons se désintègrent en leptons et photons, ou si l'univers subit une mort thermique ou s'effondre, je n'oublierai pas votre putain de scénario. Sans ton putain de scénario, je devrais suivre des cours simplement obligatoires le semestre prochain🥰

Gracias, Emmm ordinario pero grandioso, mi alma parece haber sido divinamente lavada. Miles de destinatarios recuerdan tus méritos y los devotos creyentes cantan para ti. Incluso si se producen destellos de helio en el sol, todos los bariones se desintegran en leptones y fotones, o el universo sufre muerte por calor o colapsa, no olvidaré tu jodido guión. Sin tu maldito guión, tendría que tomar cursos meramente obligatorios el próximo semestre🥰

**Comment by H4ckF0rFun** [comment]
感谢大佬的Star
